Convert updater to a quarkus app and add a route to request update of specific release
adoptium/api.adoptium.net pull request #161
Opened 2021-09-13 14:30 UTC by johnoliver

# Checklist

- [ ] You added tests to cover the change
- [ ] `mvn clean install` build and test completes
- [ ] You changed or added to the documentation

2021-09-23 10:41 UTC, gdams approved these changes

2021-09-23 10:48 UTC, tellison commented
A big PR to gulp in one go, but yes in principle.
I read through and think I convinced myself that (a) the user role sufficiently protects the updater, and that (b) the testUpdaterUser is well isolated - so that in both cases there is no opportunity for DoS by multiple update calls from untrusted parties.

2021-09-23 11:00 UTC, karianna requested changes

2021-10-02 22:07 UTC, johnoliver commented on adoptopenjdk-updater-parent/adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/routes/UpdateTrigger.kt
> +            val response = "Updating: \n" +
probably

2021-10-04 09:28 UTC, karianna approved these changes

2021-10-04 09:28 UTC, merged