add testing both adoptium and adoptopenjdk
adoptium/api.adoptium.net pull request #184
Opened 2021-09-27 22:25 UTC by johnoliver

# Checklist

- [ ] You added tests to cover the change
- [ ] `mvn clean install` build and test completes
- [ ] You changed or added to the documentation

2021-09-27 22:57 UTC, johnoliver commented on .github/workflows/build-adoptopenjdk.yml
> +      run: ./mvnw --batch-mode clean install jacoco:report jacoco:report-aggregate
it defaults to adoptopenjdk, will need to switch that at some point

2021-09-27 23:06 UTC, karianna approved these changes

2021-09-28 07:47 UTC, gdams requested changes

2021-09-28 07:47 UTC, gdams commented on .github/workflows/build-adoptium.yml
> +  build:
You could do with adding names to these job elements to prevent them just appearing as build in the UI

2021-09-28 09:26 UTC, gdams requested changes

2021-09-28 09:26 UTC, gdams commented on .github/workflows/build-adoptium.yml
> +  build:
```suggestion
  build:
  name: Build Adoptium
```

2021-09-28 09:26 UTC, gdams commented on .github/workflows/build-adoptopenjdk.yml
> +  build:
```suggestion
  build:
  name: Build AdoptOpenJDK
```

2021-09-28 12:20 UTC, sxa requested changes
ECA check failing so this shouldn't be merged yet.

Also, since it hasn't been made clear in the description, this is to support using a common codebase for the Adoptium and AdoptOpenJDK APIs

2021-10-04 09:31 UTC, gdams approved these changes

2021-10-06 00:01 UTC, merged