Contributions to v4 planning docs
adoptium/api.adoptium.net pull request #3
Opened 2021-03-27 08:38 UTC by nickebbitt

Here's are some initial thoughts to prompt discussion. 

They are based on the context/experience I have so are there to challenged by those more in the know :)

2021-03-29 00:24 UTC, johnoliver approved these changes

2021-03-29 00:26 UTC, johnoliver requested changes
I agree with the comments here, in terms of merging it, not sure I can without an eca

2021-03-29 12:18 UTC, nickebbitt commented
@johnoliver how's that now?

2021-03-30 13:50 UTC, johnoliver approved these changes

2021-03-31 16:47 UTC, karianna approved these changes
LGTM

2021-03-31 16:48 UTC, merged