Import marketplace server
adoptium/api.adoptium.net pull request #337
Opened 2022-03-07 19:19 UTC by johnoliver

# Checklist

- [ ] You added tests to cover the change
- [ ] `mvn clean install` build and test completes
- [ ] You changed or added to the documentation

2022-03-09 12:43 UTC, karianna requested changes

2022-03-09 12:43 UTC, karianna commented on adoptium-frontend-parent/adoptium-api-v3-frontend/src/test/kotlin/net/adoptium/api/VersionPathTest.kt
> +@Disabled("Temp removal to get marketplace build working")
Check if VersionPath still even exists

2022-03-09 12:43 UTC, karianna commented on marketplace/README.md
> +# Testing
More context in this README please.  Also link to this from the main README

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Binary.java
> +    @Schema(required = true, example = "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17%2B35/OpenJDK17-jdk_x64_linux_hotspot_17_35.tar.gz.aqavit.zip")
Missing descriptions, add all of those.

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/Distribution.java
> +@Schema(type = SchemaType.STRING, enumeration = {"temurin", "dragonwell", "zing", "microsoft"})
zulu not zing

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-schema/src/main/java/net/adoptium/marketplace/schema/IndexFile.java
> +            @JsonProperty(value = "indexes") List<String> indexes,
whitespace

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-assets/src/main/resources/META-INF/resources/css/style.css
> +body {
prefer em over px for actual font sizing

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-assets/src/main/resources/META-INF/resources/index.html
> +    <title>Adoptium</title>
change ttile and description to add marketplace to avoid confusion

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-assets/src/main/resources/META-INF/resources/index.html
> +    <h1>Adoptium API v3</h1>
v1

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/BinaryAssetView.kt
> +    val binary: Binary
Binary schema needs descriptions, check the others as well

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/DateTime.kt
> +import java.util.*
.* :-(

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/DateTime.kt
> +DateTime {
APIDateTime perhaps?  Not to confuse with Java DateTime

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/DateTime.kt
> +                // NOP
log?

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/DateTime.kt
> +                // NOP
Log

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/DateTime.kt
> +class DateTimeDeSerializer : JsonDeserializer<DateTime>() {
Add doc to say why we are so promiscuous :-)

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/ReleaseUpdateSummary.kt
> +import java.util.*
util.*

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend-models/src/main/kotlin/net/adoptium/marketplace/server/frontend/models/SortOrder.kt
> +@Schema(type = SchemaType.STRING, enumeration = ["ASC", "DESC"], defaultValue = "DESC")
description

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-frontend/src/main/kotlin/net/adoptium/marketplace/server/frontend/routes/AssetsResource.kt
> +    suspend fun get(
Add more descriptions

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-version-utils/src/main/kotlin/net/adoptium/api/marketplace/parser/maven/VersionParser.kt
> +/* ktlint-enable no-wildcard-imports */
remove one of these

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-version-utils/src/main/kotlin/net/adoptium/api/marketplace/parser/maven/VersionParser.kt
> +// This is a port of the Groovy VersionParser in the openjdk-build project
Add an issue for this?

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-version-utils/src/main/kotlin/net/adoptium/api/marketplace/parser/maven/InvalidVersionSpecificationException.kt
> +package net.adoptium.api.marketplace.parser.maven
Consider clean room implementations?

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-frontend-parent/adoptium-marketplace-version-utils/src/main/kotlin/net/adoptium/api/marketplace/parser/maven/InvalidVersionSpecificationException.kt
> +package net.adoptium.api.marketplace.parser.maven
Or mail Brett and ask if he's OK with signing ECA

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-persistence/src/test/kotlin/net/adoptium/marketplace/dataSources/persitence/mongo/MongoTest.kt
> +                .version(Version.V4_0_2)
Is that brittle with the version?

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/adoptium-marketplace-updater-parent/adoptium-marketplace-updater/src/main/kotlin/net/adoptium/marketplace/server/updater/AdoptiumMarketplaceUpdater.kt
> +class AdoptiumMarketplaceUpdaterApp : Application()
docs please

2022-03-09 12:43 UTC, karianna commented on marketplace/adoptium-marketplace-server/pom.xml
> +        <quarkus.version>2.7.0.Final</quarkus.version>
go to 2.7.3 and weep as your test randomly fails.  2.7.1 is fine

2022-03-09 16:24 UTC, tellison approved these changes
A big PR, that I was able to review on your fork a while ago.

Still a few tweaks to go. For example, many of the schema values are optional as they are not used by the marketplace code, so we should mark required vs. optional and let publishers decide how much info they wish to include.
However, happy to +1 this PR and continue refining it once the bulk has landed.

Thanks for all the hard work that is very apparent here @johnoliver !

2022-03-10 17:47 UTC, karianna approved these changes

2022-03-10 17:48 UTC, karianna commented
@johnoliver Happy with this now - feel free to self merge as you see fit.

2022-03-24 13:22 UTC, tellison commented
@karianna @johnoliver please confirm this is now good to merge?

2022-03-25 11:48 UTC, merged